version: "3.8"

services:
  mongo:
    container_name: mongo
    image: mongo:8.0.4
    command: []
    restart: always
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/mongo:/data/db
    ports:
      - 27017:27017
    networks:
      - web-network

  redis:
    container_name: redis
    image: redis:7.4.2
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 60 1
    volumes: 
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/redis:/data
    networks:
      - web-network

  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
      target: next
      network: host
      args:
        - APP_NAME=web
    restart: always
    ports:
      - 3000:3000
    networks:
      - web-network
    depends_on:
      - mongo
      - redis

  worker:
    container_name: worker
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
      args:
        - APP_NAME=worker
    restart: always
    networks:
      - web-network
    depends_on:
      - mongo
      - redis

networks:
  web-network: